name: Send tweet to cryptoprices365 twitter account with price info

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # Action runs every hour

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Set up Python 3.9
        uses: actions/setup-python@v2 # for setting up a Python environment on the github runner --> https://github.com/actions/setup-python
        with:
          python-version: 3.9
          
      # This task installs the required dependences of the python program, based on what is in the requirements.txt file in the repo.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Runs a set of commands using the runners shell
      - name: execute python script
        run: python static_license_count_site.py
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
